terraform {
  required_version = ">= 1.7.0"
}

variable "promotion_manifest_file" {
  description = "Path to the JSON manifest generated by cxdeploy export-manifest."
  type        = string
}

locals {
  promotion_manifest = jsondecode(file(var.promotion_manifest_file))
  resources = {
    for item in local.promotion_manifest.ordered_resources : item.id => item
  }
}

# This platform-neutral resource models stable lifecycle and change detection.
# Replace or extend it with the approved provider/API adapter for the target.
resource "terraform_data" "configuration_resource" {
  for_each = local.resources

  input = {
    sequence   = each.value.sequence
    kind       = each.value.kind
    depends_on = each.value.depends_on
    config     = each.value.config
  }

  triggers_replace = [
    each.value.digest
  ]
}

output "ordered_resource_ids" {
  description = "Dependency-ordered resource identifiers."
  value = [
    for item in local.promotion_manifest.ordered_resources : item.id
  ]
}

